---
apiVersion: v1
kind: Service
metadata:
  name: health-agent-metrics
  namespace: demo
  labels:
    app: health-agent
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app: health-agent
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-agent
  namespace: demo
  labels:
    app: health-agent
    release: prometheus
spec:
  selector:
    matchLabels:
      app: health-agent
  endpoints:
    - port: http
      interval: 15s
      scrapeTimeout: 10s
      path: /metrics
